name: CI/CD Pipeline Pasteleria

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # --- AGREGA ESTE BLOQUE EXACTAMENTE AQUÍ ---
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "Pollitos12!"  # Tu contraseña de application.properties
          MYSQL_DATABASE: pasteles            # Tu base de datos
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    # -------------------------------------------

    strategy:
      matrix:
        service: [micro-core, micro-carrito, micro-usuarios] 

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Correr Tests con Maven
      # Recuerda mantener la ruta corregida que vimos antes
      working-directory: ./Equipo10_Caceres-Turra-main/${{ matrix.service }}
      run: mvn test

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y Subir Imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: ./Equipo10_Caceres-Turra-main/${{ matrix.service }}
        file: ./Equipo10_Caceres-Turra-main/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest