name: CI/CD Pipeline Pasteleria

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: "Pollitos12!"
          MYSQL_DATABASE: pasteles
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    strategy:
      matrix:
        service: [micro-core, micro-carrito, micro-usuarios] 

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Correr Tests con Maven
      working-directory: ./Equipo10_Caceres-Turra-main/${{ matrix.service }}
      run: mvn test

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y Subir Imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: ./Equipo10_Caceres-Turra-main/${{ matrix.service }}
        file: ./Equipo10_Caceres-Turra-main/${{ matrix.service }}/Dockerfile
        push: true

        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest


  deploy-to-cloud:
    needs: build-and-push 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

 
      - name: Copiar configuración a la nube via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          source: "Equipo10_Caceres-Turra-main/docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}/deploy"


      - name: Ejecutar configuración remota via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 1. ENVIAMOS EL SECRETO COMO VARIABLE DE ENTORNO
          envs: AZURE_SB_CONNECTION_STRING 
          script: |
            # 2. EXPORTAMOS LA VARIABLE EN EL SERVIDOR
            export AZURE_SB_CONNECTION_STRING=$AZURE_SB_CONNECTION_STRING
            
            cd /home/${{ secrets.SSH_USERNAME }}/deploy/Equipo10_Caceres-Turra-main
            docker-compose pull
            
            # 3. DESPLEGAMOS (Docker leerá la variable exportada)
            docker stack deploy -c docker-compose.yml pasteleria
        env:
            # 4. LE DECIMOS A GITHUB QUE PASE EL SECRETO AL ACTION
            AZURE_SB_CONNECTION_STRING: ${{ secrets.AZURE_SB_CONNECTION_STRING }}